Merged "PCRE" library with the SourceForge VCS:
18. At a user's suggestion, the macros GETCHAR and friends (which pick up UTF-8
    characters from a string of bytes) have been redefined so as not to use
    loops, in order to improve performance in some environments. At the same
    time, I abstracted some of the common code into auxiliary macros to save
    repetition (this should not affect the compiled code).

19. If \c was followed by a multibyte UTF-8 character, bad things happened. A
    compile-time error is now given if \c is not followed by an ASCII
    character, that is, a byte less than 128. (In EBCDIC mode, the code is
    different, and any byte value is allowed.)

20. Recognize (*NO_START_OPT) at the start of a pattern to set the PCRE_NO_
    START_OPTIMIZE option, which is now allowed at compile time - but just
    passed through to pcre_exec() or pcre_dfa_exec(). This makes it available
    to pcregrep and other applications that have no direct access to PCRE
    options. The new /Y option in pcretest sets this option when calling
    pcre_compile().

21. Change 18 of release 8.01 broke the use of named subpatterns for recursive
    back references. Groups containing recursive back references were forced to
    be atomic by that change, but in the case of named groups, the amount of
    memory required was incorrectly computed, leading to "Failed: internal
    error: code overflow". This has been fixed.

22. Some patches to pcre_stringpiece.h, pcre_stringpiece_unittest.cc, and
    pcretest.c, to avoid build problems in some Borland environments.